
create extension if not exists pgcrypto;

create table if not exists public.powerups9000_ups (
  id uuid primary key default gen_random_uuid(),
  serial_no text not null unique,
  project_type text not null check (project_type in ('ADANI','RELIANCE','STANDARD')),
  current_stage text not null check (
    current_stage in ('RECEIVED','UNDER_TESTING','HEATRUN_PROGRESS','HEATRUN_COMPLETED','FAT_PROGRESS','TO_FINISHING')
  ),
  previous_stage text,
  first_received_at timestamptz,
  last_updated_at timestamptz not null default now(),
  updated_by text default 'QR_SCAN',
  created_at timestamptz not null default now()
);

create table if not exists public.powerups9000_scan_history (
  id bigint generated by default as identity primary key,
  serial_no text not null,
  project_type text not null check (project_type in ('ADANI','RELIANCE','STANDARD')),
  stage text not null check (
    stage in ('RECEIVED','UNDER_TESTING','HEATRUN_PROGRESS','HEATRUN_COMPLETED','FAT_PROGRESS','TO_FINISHING')
  ),
  scanned_at timestamptz not null default now(),
  source text not null default 'QR_SCAN'
);

create index if not exists idx_p9k_ups_stage on public.powerups9000_ups(current_stage);
create index if not exists idx_p9k_ups_project on public.powerups9000_ups(project_type);
create index if not exists idx_p9k_history_time on public.powerups9000_scan_history(scanned_at desc);
create index if not exists idx_p9k_history_serial on public.powerups9000_scan_history(serial_no);

create or replace function public.powerups9000_scan_update(
  p_serial_no text,
  p_project_type text,
  p_stage text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_serial text := upper(trim(p_serial_no));
  v_project text := upper(trim(p_project_type));
  v_stage text := upper(trim(p_stage));
  v_prev text;
  v_last timestamptz;
begin
  if v_serial is null or length(v_serial)=0 then
    raise exception 'Serial number is required';
  end if;

  if v_project not in ('ADANI','RELIANCE','STANDARD') then
    raise exception 'Invalid project type';
  end if;

  if v_stage not in ('RECEIVED','UNDER_TESTING','HEATRUN_PROGRESS','HEATRUN_COMPLETED','FAT_PROGRESS','TO_FINISHING') then
    raise exception 'Invalid stage';
  end if;

  if v_project in ('RELIANCE','STANDARD') and v_stage='FAT_PROGRESS' then
    raise exception 'FAT stage is not allowed for Reliance or Standard';
  end if;

  select current_stage,last_updated_at
    into v_prev,v_last
    from public.powerups9000_ups
   where serial_no=v_serial;

  if v_prev=v_stage and v_last is not null and now()-v_last < interval '5 seconds' then
    return jsonb_build_object(
      'ok',true,
      'duplicate_ignored',true,
      'serial_no',v_serial,
      'project_type',v_project,
      'stage',v_stage
    );
  end if;

  insert into public.powerups9000_ups(
    serial_no,project_type,current_stage,previous_stage,
    first_received_at,last_updated_at,updated_by
  )
  values(
    v_serial,v_project,v_stage,null,
    case when v_stage='RECEIVED' then now() else null end,
    now(),'QR_SCAN'
  )
  on conflict(serial_no)
  do update set
    project_type=excluded.project_type,
    previous_stage=public.powerups9000_ups.current_stage,
    current_stage=excluded.current_stage,
    first_received_at=coalesce(
      public.powerups9000_ups.first_received_at,
      case when excluded.current_stage='RECEIVED' then now() else null end
    ),
    last_updated_at=now(),
    updated_by='QR_SCAN';

  insert into public.powerups9000_scan_history(serial_no,project_type,stage,source)
  values(v_serial,v_project,v_stage,'QR_SCAN');

  return jsonb_build_object(
    'ok',true,
    'duplicate_ignored',false,
    'serial_no',v_serial,
    'project_type',v_project,
    'stage',v_stage
  );
end;
$$;

alter table public.powerups9000_ups enable row level security;
alter table public.powerups9000_scan_history enable row level security;

drop policy if exists "p9k read ups" on public.powerups9000_ups;
create policy "p9k read ups"
on public.powerups9000_ups
for select
to anon,authenticated
using(true);

drop policy if exists "p9k read history" on public.powerups9000_scan_history;
create policy "p9k read history"
on public.powerups9000_scan_history
for select
to anon,authenticated
using(true);

revoke insert,update,delete on public.powerups9000_ups from anon,authenticated;
revoke insert,update,delete on public.powerups9000_scan_history from anon,authenticated;

grant select on public.powerups9000_ups to anon,authenticated;
grant select on public.powerups9000_scan_history to anon,authenticated;
grant execute on function public.powerups9000_scan_update(text,text,text) to anon,authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='powerups9000_ups'
  ) then
    alter publication supabase_realtime add table public.powerups9000_ups;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='powerups9000_scan_history'
  ) then
    alter publication supabase_realtime add table public.powerups9000_scan_history;
  end if;
end $$;
